### 1. Self Attention - Math
- Objective to implement scaled dot product attention

In [7]:
import numpy as np

rndGen = np.random.default_rng()

In [17]:
Q = rndGen.random((5,5))
K = rndGen.random((5,5))
V = rndGen.random((5,5))
dK = K.shape[0] #In real life this wont be a sq matrix, we will have to take shape[1], So K's dim will be (number of words, dimK)

In [18]:
def softmax(X):
    X = X - np.max(X, axis=1, keepdims=True)

    expX = np.exp(X)

    return expX / np.sum(expX, axis=1, keepdims=True)

In [14]:
sftOut = softmax(np.dot(Q,K.T) / np.sqrt(dK))
SelfAttention = np.dot(sftOut, V)

In [15]:
print(SelfAttention)

[[0.54685944 0.5532422  0.46821033 0.36160719 0.75087086]
 [0.55184931 0.54116011 0.4645413  0.34807289 0.74947501]
 [0.53838627 0.55553182 0.47662506 0.37436722 0.75304106]
 [0.55404608 0.54213603 0.48151791 0.39670051 0.74545611]
 [0.5492613  0.55178954 0.48864833 0.38166186 0.7560972 ]]


### 2. Self Attention - Real Life Scenario
- Objective to implement scaled dot product attention, close to the real life scenario

In [38]:
import numpy as np

np.random.seed(42)
tokens = ["The", "cat", "sat", "on", "the", "mat"]

seqLen = len(tokens)
embdDim = 8

# Random embeddings
embeddings = np.random.randn(seqLen, embdDim)
embeddings.shape

(6, 8)

In [34]:
wQ = np.random.randn(embdDim, embdDim)
wK = np.random.randn(embdDim, embdDim)
wV = np.random.randn(embdDim, embdDim)

Q = embeddings @ wQ
K = embeddings @ wK
V = embeddings @ wV

In [39]:
Q.shape

(6, 8)

In [36]:
dK = K.shape[1]

scores = Q @ K.T / np.sqrt(dK)

print(scores.shape)

(6, 6)


In [37]:
attention_weights = softmax(scores)

np.set_printoptions(precision=3, suppress=True)
print(attention_weights)

[[0.    0.003 0.    0.    0.997 0.   ]
 [1.    0.    0.    0.    0.    0.   ]
 [0.897 0.    0.001 0.094 0.    0.008]
 [0.057 0.012 0.053 0.878 0.    0.001]
 [1.    0.    0.    0.    0.    0.   ]
 [0.907 0.    0.    0.092 0.    0.   ]]
